// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUsernameById = `-- name: GetUsernameById :one
SELECT name FROM users WHERE id = $1
`

func (q *Queries) GetUsernameById(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUsernameById, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
